services:
  mariadb:
    image: mariadb:latest
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    restart: always
    ports:
      - '3306:3306'
    # volumes:
    #   - ./StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
    #   - ./StirlingPDF/extraConfigs:/configs
    #   - ./StirlingPDF/customFiles:/customFiles/
    #   - ./StirlingPDF/logs:/logs/
    #   - ./StirlingPDF/pipeline:/pipeline/
    environment:
      - MARIADB_ROOT_PASSWORD=password
      - MARIADB_DATABASE=database
